-- Compliance Reports Table
-- Tracks who reported whom, for what reason, and what action was taken

create table if not exists compliance_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null,
  reported_id uuid not null,
  reason_id bigint references master_report_reasons(id),
  description text,
  action_taken text default 'pending', -- pending, warning, account_suspended, account_banned, dismissed
  action_details text,
  actioned_by uuid, -- admin who took the action
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_compliance_reports_reporter on compliance_reports(reporter_id);
create index if not exists idx_compliance_reports_reported on compliance_reports(reported_id);
create index if not exists idx_compliance_reports_created on compliance_reports(created_at);

-- Grievance Tickets Table
-- Structured ticketing system for user complaints (DPDP Act / IT Rules 2021 compliance)

create table if not exists grievance_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  category text not null check (category in ('data_privacy', 'account', 'content', 'safety', 'payment', 'other')),
  subject text not null,
  description text not null,
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  status text not null default 'open' check (status in ('open', 'acknowledged', 'in_progress', 'resolved', 'closed')),
  assigned_to text, -- admin email or name
  response text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_grievance_tickets_user on grievance_tickets(user_id);
create index if not exists idx_grievance_tickets_status on grievance_tickets(status);
create index if not exists idx_grievance_tickets_created on grievance_tickets(created_at);

-- User Consents Table (DPDP Act compliance)
-- Tracks what the user has consented to and when

create table if not exists user_consents (
  user_id uuid primary key references auth.users(id) on delete cascade,
  age_consent boolean default false,
  terms_accepted boolean default false,
  privacy_accepted boolean default false,
  guidelines_accepted boolean default false,
  data_processing_accepted boolean default false,
  terms_accepted_at timestamptz,
  privacy_accepted_at timestamptz,
  guidelines_accepted_at timestamptz,
  data_processing_accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
